import {MigrationInterface, QueryRunner} from "typeorm";

export class firtMigration1628803998952 implements MigrationInterface {
    name = 'firtMigration1628803998952'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "transformador_history" DROP CONSTRAINT "FK_49a611aee89b4888fc40fae3b83"`);
        await queryRunner.query(`ALTER TABLE "transformador" DROP CONSTRAINT "FK_0811119ad82d3f12b8868e7886f"`);
        await queryRunner.query(`ALTER TABLE "transformador" DROP CONSTRAINT "FK_1dbc5c073b79860a90a4f0a5357"`);
        await queryRunner.query(`ALTER TABLE "transformador" DROP CONSTRAINT "FK_2fdec658590e3659e8264437cbe"`);
        await queryRunner.query(`ALTER TABLE "transformador" DROP CONSTRAINT "FK_033c270499f6016fbe8ce8109f4"`);
        await queryRunner.query(`ALTER TABLE "transformador" DROP CONSTRAINT "FK_5735d8b4e488bf40c02d6235eae"`);
        await queryRunner.query(`ALTER TABLE "transformador" DROP CONSTRAINT "FK_25168a4af0dc7dee21b9060ff9c"`);
        await queryRunner.query(`ALTER TABLE "transformador" DROP CONSTRAINT "FK_d5dcfb16a204473788f69a57c63"`);
        await queryRunner.query(`ALTER TABLE "transformador" DROP CONSTRAINT "FK_a39a2fc8d1fd728d443dfa23507"`);
        await queryRunner.query(`ALTER TABLE "transformador" DROP CONSTRAINT "FK_e7f25b0482d13195e4c08807c2c"`);
        await queryRunner.query(`ALTER TABLE "transformador" DROP CONSTRAINT "FK_9b63dde044777cafa4f268b8ba9"`);
        await queryRunner.query(`ALTER TABLE "transformador" DROP CONSTRAINT "FK_491465c988d13ad4ba1702439b6"`);
        await queryRunner.query(`ALTER TABLE "transformador" DROP CONSTRAINT "FK_964e13208e8b5916303b1fe3729"`);
        await queryRunner.query(`ALTER TABLE "transformador" DROP CONSTRAINT "FK_911c5b898a45f67be711fb7f1bf"`);
        await queryRunner.query(`ALTER TABLE "transformador" DROP CONSTRAINT "FK_a8e4b8f5b885febe2dcd413f1a4"`);
        await queryRunner.query(`ALTER TABLE "transformador" DROP CONSTRAINT "FK_7607ee4991b934b0e877a790abc"`);
        await queryRunner.query(`ALTER TABLE "transformador" DROP CONSTRAINT "FK_48780be18e0949239689231edd3"`);
        await queryRunner.query(`ALTER TABLE "transformador" DROP CONSTRAINT "FK_f1ef0c13a22619d647cc66093ba"`);
        await queryRunner.query(`ALTER TABLE "proyecto" RENAME COLUMN "id_proyecto" TO "proyectoId"`);
        await queryRunner.query(`ALTER TABLE "proyecto" RENAME CONSTRAINT "PK_5ecc7af27ab7fa5ed5243d437c4" TO "PK_696214b6444b9d109f850c82367"`);
        await queryRunner.query(`ALTER SEQUENCE "proyecto_id_proyecto_seq" RENAME TO "proyecto_proyectoId_seq"`);
        await queryRunner.query(`ALTER TABLE "transformadores_capacidades" RENAME COLUMN "id_capacidad" TO "capacidadId"`);
        await queryRunner.query(`ALTER TABLE "transformadores_capacidades" RENAME CONSTRAINT "PK_4d5d9842b4f280405d736e98671" TO "PK_875e138bf3b3069e7b65c7e6f91"`);
        await queryRunner.query(`ALTER SEQUENCE "transformadores_capacidades_id_capacidad_seq" RENAME TO "transformadores_capacidades_capacidadId_seq"`);
        await queryRunner.query(`ALTER TABLE "transformadores_conexiones" RENAME COLUMN "id_conexion" TO "conexionId"`);
        await queryRunner.query(`ALTER TABLE "transformadores_conexiones" RENAME CONSTRAINT "PK_771c4032e20dce521e09b5524fd" TO "PK_b065af150910fd14b0afd587cab"`);
        await queryRunner.query(`ALTER SEQUENCE "transformadores_conexiones_id_conexion_seq" RENAME TO "transformadores_conexiones_conexionId_seq"`);
        await queryRunner.query(`ALTER TABLE "transformadores_efecto" RENAME COLUMN "id_efecto" TO "efectoId"`);
        await queryRunner.query(`ALTER TABLE "transformadores_efecto" RENAME CONSTRAINT "PK_af57613b05f91684990faa28ab5" TO "PK_dc6c0ce8ed39e021e1d076d1903"`);
        await queryRunner.query(`ALTER SEQUENCE "transformadores_efecto_id_efecto_seq" RENAME TO "transformadores_efecto_efectoId_seq"`);
        await queryRunner.query(`ALTER TABLE "transformadores_estados" RENAME COLUMN "id_estado" TO "estadoId"`);
        await queryRunner.query(`ALTER TABLE "transformadores_estados" RENAME CONSTRAINT "PK_df6bac6af1079e757686d988ac4" TO "PK_d00dac79de670d9c19260e0fa67"`);
        await queryRunner.query(`ALTER SEQUENCE "transformadores_estados_id_estado_seq" RENAME TO "transformadores_estados_estadoId_seq"`);
        await queryRunner.query(`ALTER TABLE "transformadores_resultados_evaluacion" RENAME COLUMN "id_resultado" TO "resultadoEvaluacionId"`);
        await queryRunner.query(`ALTER TABLE "transformadores_resultados_evaluacion" RENAME CONSTRAINT "PK_d6a952504dab1d399e57479e6aa" TO "PK_20d2cbc6e75e182556df2febbde"`);
        await queryRunner.query(`ALTER SEQUENCE "transformadores_resultados_evaluacion_id_resultado_seq" RENAME TO "transformadores_resultados_evaluacion_resultadoEvaluacionId_seq"`);
        await queryRunner.query(`ALTER TABLE "transformadores_fabricantes" RENAME COLUMN "id_fabricante" TO "fabricanteId"`);
        await queryRunner.query(`ALTER TABLE "transformadores_fabricantes" RENAME CONSTRAINT "PK_82d72a72eacec5188ad9df70c71" TO "PK_96ff1c88cbe4a1d56233987f1c2"`);
        await queryRunner.query(`ALTER SEQUENCE "transformadores_fabricantes_id_fabricante_seq" RENAME TO "transformadores_fabricantes_fabricanteId_seq"`);
        await queryRunner.query(`ALTER TABLE "transformadores_fases" RENAME COLUMN "id_fase" TO "faseId"`);
        await queryRunner.query(`ALTER TABLE "transformadores_fases" RENAME CONSTRAINT "PK_3c676769b9d2ce253994d947e83" TO "PK_20749f59de4212e35823bc06c09"`);
        await queryRunner.query(`ALTER SEQUENCE "transformadores_fases_id_fase_seq" RENAME TO "transformadores_fases_faseId_seq"`);
        await queryRunner.query(`ALTER TABLE "transformadores_propiedad" RENAME COLUMN "id_propiedad" TO "propiedadId"`);
        await queryRunner.query(`ALTER TABLE "transformadores_propiedad" RENAME CONSTRAINT "PK_d647dbb6eb5d7931fc47462d8b5" TO "PK_6adcff562dbe44c73e3d37fd4ad"`);
        await queryRunner.query(`ALTER SEQUENCE "transformadores_propiedad_id_propiedad_seq" RENAME TO "transformadores_propiedad_propiedadId_seq"`);
        await queryRunner.query(`ALTER TABLE "transformadores_razones_rechazo" RENAME COLUMN "id_razon" TO "razonRechazoId"`);
        await queryRunner.query(`ALTER TABLE "transformadores_razones_rechazo" RENAME CONSTRAINT "PK_e5984dbf9e1dcbb8a9def0d0118" TO "PK_058530b50659ab358b9c35b4567"`);
        await queryRunner.query(`ALTER SEQUENCE "transformadores_razones_rechazo_id_razon_seq" RENAME TO "transformadores_razones_rechazo_razonRechazoId_seq"`);
        await queryRunner.query(`ALTER TABLE "transformadores_regulaciones" RENAME COLUMN "id_regulacion" TO "regulacionId"`);
        await queryRunner.query(`ALTER TABLE "transformadores_regulaciones" RENAME CONSTRAINT "PK_630f22d451333479bd1bfd41d91" TO "PK_801e2d41d7541bf7ee2ed103bcf"`);
        await queryRunner.query(`ALTER SEQUENCE "transformadores_regulaciones_id_regulacion_seq" RENAME TO "transformadores_regulaciones_regulacionId_seq"`);
        await queryRunner.query(`ALTER TABLE "transformadores_soportes" RENAME COLUMN "id_soporte" TO "soporteId"`);
        await queryRunner.query(`ALTER TABLE "transformadores_soportes" RENAME CONSTRAINT "PK_c2e5519a97aed89f951b9125fde" TO "PK_7c8bd6cc594d72b2865244362d2"`);
        await queryRunner.query(`ALTER SEQUENCE "transformadores_soportes_id_soporte_seq" RENAME TO "transformadores_soportes_soporteId_seq"`);
        await queryRunner.query(`ALTER TABLE "transformadores_suplidores" RENAME COLUMN "id_suplidor" TO "suplidorId"`);
        await queryRunner.query(`ALTER TABLE "transformadores_suplidores" RENAME CONSTRAINT "PK_76510d1d136e8d1834c286de77c" TO "PK_5d77c13ae641f238e6ecad9f03b"`);
        await queryRunner.query(`ALTER SEQUENCE "transformadores_suplidores_id_suplidor_seq" RENAME TO "transformadores_suplidores_suplidorId_seq"`);
        await queryRunner.query(`ALTER TABLE "transformadores_tension_primaria" RENAME COLUMN "id_tension_primaria" TO "tensionPrimariaId"`);
        await queryRunner.query(`ALTER TABLE "transformadores_tension_primaria" RENAME CONSTRAINT "PK_b147cc945f0c090bc6217a054bd" TO "PK_c09d6bd5e2ef3ce051cd2230a36"`);
        await queryRunner.query(`ALTER SEQUENCE "transformadores_tension_primaria_id_tension_primaria_seq" RENAME TO "transformadores_tension_primaria_tensionPrimariaId_seq"`);
        await queryRunner.query(`ALTER TABLE "transformadores_tension_secundaria" RENAME COLUMN "id_tension_secundaria" TO "tensionSecundariaId"`);
        await queryRunner.query(`ALTER TABLE "transformadores_tension_secundaria" RENAME CONSTRAINT "PK_ab0ca604c7ffc6ab3e506e6b35f" TO "PK_a6998508c1973c6b7c0e039db63"`);
        await queryRunner.query(`ALTER SEQUENCE "transformadores_tension_secundaria_id_tension_secundaria_seq" RENAME TO "transformadores_tension_secundaria_tensionSecundariaId_seq"`);
        await queryRunner.query(`ALTER TABLE "transformadores_tipo_reparacion" RENAME COLUMN "id_tipo_reparacion" TO "tipoReparacionId"`);
        await queryRunner.query(`ALTER TABLE "transformadores_tipo_reparacion" RENAME CONSTRAINT "PK_2d1dc5624e4a0c26f436065d457" TO "PK_49202691f772e3f1cbd062da25e"`);
        await queryRunner.query(`ALTER SEQUENCE "transformadores_tipo_reparacion_id_tipo_reparacion_seq" RENAME TO "transformadores_tipo_reparacion_tipoReparacionId_seq"`);
        await queryRunner.query(`ALTER TABLE "transformadores_ubicacion" RENAME COLUMN "id_ubicacion" TO "ubicacionId"`);
        await queryRunner.query(`ALTER TABLE "transformadores_ubicacion" RENAME CONSTRAINT "PK_385f8f855d9cfacec35b43f2738" TO "PK_124a7e146c6342fddc827714bf6"`);
        await queryRunner.query(`ALTER SEQUENCE "transformadores_ubicacion_id_ubicacion_seq" RENAME TO "transformadores_ubicacion_ubicacionId_seq"`);
        await queryRunner.query(`ALTER TABLE "transformadores_unidades_constructiva" RENAME COLUMN "id_unidad" TO "unidadId"`);
        await queryRunner.query(`ALTER TABLE "transformadores_unidades_constructiva" RENAME CONSTRAINT "PK_62e8d7d29ae24f63be4f2bd2c15" TO "PK_4e341b5338c1d26b0f4eb847bd1"`);
        await queryRunner.query(`ALTER SEQUENCE "transformadores_unidades_constructiva_id_unidad_seq" RENAME TO "transformadores_unidades_constructiva_unidadId_seq"`);
        await queryRunner.query(`ALTER TABLE "transformadores_valoraciones" RENAME COLUMN "id_valoracion" TO "valoracionId"`);
        await queryRunner.query(`ALTER TABLE "transformadores_valoraciones" RENAME CONSTRAINT "PK_dc50231888c0809221e561a7def" TO "PK_e93a53b867248142f4546b1998b"`);
        await queryRunner.query(`ALTER SEQUENCE "transformadores_valoraciones_id_valoracion_seq" RENAME TO "transformadores_valoraciones_valoracionId_seq"`);
        await queryRunner.query(`ALTER TABLE "transformadores_tipo_soportes" DROP CONSTRAINT "PK_a6dd05052e83b7fd1508bdadc68"`);
        await queryRunner.query(`ALTER TABLE "transformadores_tipo_soportes" DROP COLUMN "id_tipo_soporte"`);
        await queryRunner.query(`ALTER TABLE "transformadores_tipo_soportes" DROP CONSTRAINT "UQ_b0fe91b2b70fcca603cf7d2ff93"`);
        await queryRunner.query(`ALTER TABLE "transformadores_tipo_soportes" DROP COLUMN "tipo_soporte"`);
        await queryRunner.query(`ALTER TABLE "transformador_history" DROP CONSTRAINT "PK_0085c3c9b93a0379203566f79ab"`);
        await queryRunner.query(`ALTER TABLE "transformador_history" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "transformador_history" DROP COLUMN "nombreProyecto"`);
        await queryRunner.query(`ALTER TABLE "transformador_history" DROP COLUMN "codigoProyecto"`);
        await queryRunner.query(`ALTER TABLE "transformador_history" DROP COLUMN "codigoSap"`);
        await queryRunner.query(`ALTER TABLE "transformador_history" DROP CONSTRAINT "UQ_49a611aee89b4888fc40fae3b83"`);
        await queryRunner.query(`ALTER TABLE "transformador_history" DROP COLUMN "usuarioIdUsuarioId"`);
        await queryRunner.query(`ALTER TABLE "transformador" DROP CONSTRAINT "PK_ff9524e64fceca6e12d390d71c5"`);
        await queryRunner.query(`ALTER TABLE "transformador" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "transformador" DROP COLUMN "id_suplidor"`);
        await queryRunner.query(`ALTER TABLE "transformador" DROP COLUMN "id_valoracion"`);
        await queryRunner.query(`ALTER TABLE "transformador" DROP COLUMN "id_soporte"`);
        await queryRunner.query(`ALTER TABLE "transformador" DROP COLUMN "id_tipo_soporte"`);
        await queryRunner.query(`ALTER TABLE "transformador" DROP COLUMN "id_fabricante"`);
        await queryRunner.query(`ALTER TABLE "transformador" DROP COLUMN "id_fase"`);
        await queryRunner.query(`ALTER TABLE "transformador" DROP COLUMN "id_capacidad"`);
        await queryRunner.query(`ALTER TABLE "transformador" DROP COLUMN "id_conexion"`);
        await queryRunner.query(`ALTER TABLE "transformador" DROP COLUMN "id_tension_primaria"`);
        await queryRunner.query(`ALTER TABLE "transformador" DROP COLUMN "id_tension_secundaria"`);
        await queryRunner.query(`ALTER TABLE "transformador" DROP COLUMN "id_regulacion"`);
        await queryRunner.query(`ALTER TABLE "transformador" DROP COLUMN "id_estado"`);
        await queryRunner.query(`ALTER TABLE "transformador" DROP COLUMN "id_ubicacion"`);
        await queryRunner.query(`ALTER TABLE "transformador" DROP COLUMN "id_propiedad"`);
        await queryRunner.query(`ALTER TABLE "transformador" DROP COLUMN "id_proyecto"`);
        await queryRunner.query(`ALTER TABLE "transformador" DROP COLUMN "id_efecto"`);
        await queryRunner.query(`ALTER TABLE "transformador" DROP COLUMN "id_unidad"`);
        await queryRunner.query(`ALTER TABLE "transformadores_tipo_soportes" ADD "tipoSoporteId" SERIAL NOT NULL`);
        await queryRunner.query(`ALTER TABLE "transformadores_tipo_soportes" ADD CONSTRAINT "PK_8839f8c08c17419816a22b3e303" PRIMARY KEY ("tipoSoporteId")`);
        await queryRunner.query(`ALTER TABLE "transformadores_tipo_soportes" ADD "tipoSoporte" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "transformadores_tipo_soportes" ADD CONSTRAINT "UQ_668d39a1a240327ffb49201f9b2" UNIQUE ("tipoSoporte")`);
        await queryRunner.query(`ALTER TABLE "transformador_history" ADD "transformadorId" SERIAL NOT NULL`);
        await queryRunner.query(`ALTER TABLE "transformador_history" ADD CONSTRAINT "PK_178e12c3a9f7ee66001d33763f0" PRIMARY KEY ("transformadorId")`);
        await queryRunner.query(`ALTER TABLE "transformador_history" ADD "usuarioId" integer`);
        await queryRunner.query(`ALTER TABLE "transformador_history" ADD "proyectoId" integer`);
        await queryRunner.query(`ALTER TABLE "transformador_history" ADD "unidadId" integer`);
        await queryRunner.query(`ALTER TABLE "transformador" ADD "transformadorId" SERIAL NOT NULL`);
        await queryRunner.query(`ALTER TABLE "transformador" ADD CONSTRAINT "PK_203aa7cf691c0663fe5ac65b023" PRIMARY KEY ("transformadorId")`);
        await queryRunner.query(`ALTER TABLE "transformador" ADD "suplidorId" integer`);
        await queryRunner.query(`ALTER TABLE "transformador" ADD "valoracionId" integer`);
        await queryRunner.query(`ALTER TABLE "transformador" ADD "soporteId" integer`);
        await queryRunner.query(`ALTER TABLE "transformador" ADD "tipoSoporteId" integer`);
        await queryRunner.query(`ALTER TABLE "transformador" ADD "fabricanteId" integer`);
        await queryRunner.query(`ALTER TABLE "transformador" ADD "faseId" integer`);
        await queryRunner.query(`ALTER TABLE "transformador" ADD "capacidadId" integer`);
        await queryRunner.query(`ALTER TABLE "transformador" ADD "conexionId" integer`);
        await queryRunner.query(`ALTER TABLE "transformador" ADD "tensionPrimariaId" integer`);
        await queryRunner.query(`ALTER TABLE "transformador" ADD "tensionSecundariaId" integer`);
        await queryRunner.query(`ALTER TABLE "transformador" ADD "regulacionId" integer`);
        await queryRunner.query(`ALTER TABLE "transformador" ADD "estadoId" integer`);
        await queryRunner.query(`ALTER TABLE "transformador" ADD "ubicacionId" integer`);
        await queryRunner.query(`ALTER TABLE "transformador" ADD "propiedadId" integer`);
        await queryRunner.query(`ALTER TABLE "transformador" ADD "proyectoId" integer`);
        await queryRunner.query(`ALTER TABLE "transformador" ADD "efectoId" integer`);
        await queryRunner.query(`ALTER TABLE "transformador" ADD "unidadId" integer`);
        await queryRunner.query(`ALTER TABLE "transformador_history" DROP COLUMN "matricula"`);
        await queryRunner.query(`ALTER TABLE "transformador_history" ADD "matricula" character varying(6) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "transformador_history" ALTER COLUMN "suplidorId" DROP NOT NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "transformador_history"."suplidorId" IS NULL`);
        await queryRunner.query(`ALTER TABLE "transformador_history" ALTER COLUMN "valoracionId" DROP NOT NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "transformador_history"."valoracionId" IS NULL`);
        await queryRunner.query(`ALTER TABLE "transformador_history" ALTER COLUMN "soporteId" DROP NOT NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "transformador_history"."soporteId" IS NULL`);
        await queryRunner.query(`ALTER TABLE "transformador_history" ALTER COLUMN "tipoSoporteId" DROP NOT NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "transformador_history"."tipoSoporteId" IS NULL`);
        await queryRunner.query(`ALTER TABLE "transformador_history" ALTER COLUMN "fabricanteId" DROP NOT NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "transformador_history"."fabricanteId" IS NULL`);
        await queryRunner.query(`ALTER TABLE "transformador_history" ALTER COLUMN "faseId" DROP NOT NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "transformador_history"."faseId" IS NULL`);
        await queryRunner.query(`ALTER TABLE "transformador_history" ALTER COLUMN "capacidadId" DROP NOT NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "transformador_history"."capacidadId" IS NULL`);
        await queryRunner.query(`ALTER TABLE "transformador_history" ALTER COLUMN "conexionId" DROP NOT NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "transformador_history"."conexionId" IS NULL`);
        await queryRunner.query(`ALTER TABLE "transformador_history" ALTER COLUMN "tensionPrimariaId" DROP NOT NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "transformador_history"."tensionPrimariaId" IS NULL`);
        await queryRunner.query(`ALTER TABLE "transformador_history" ALTER COLUMN "tensionSecundariaId" DROP NOT NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "transformador_history"."tensionSecundariaId" IS NULL`);
        await queryRunner.query(`ALTER TABLE "transformador_history" ALTER COLUMN "regulacionId" DROP NOT NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "transformador_history"."regulacionId" IS NULL`);
        await queryRunner.query(`ALTER TABLE "transformador_history" ALTER COLUMN "razonRechazoId" DROP NOT NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "transformador_history"."razonRechazoId" IS NULL`);
        await queryRunner.query(`ALTER TABLE "transformador_history" ALTER COLUMN "estadoId" DROP NOT NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "transformador_history"."estadoId" IS NULL`);
        await queryRunner.query(`ALTER TABLE "transformador_history" ALTER COLUMN "ubicacionId" DROP NOT NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "transformador_history"."ubicacionId" IS NULL`);
        await queryRunner.query(`ALTER TABLE "transformador_history" ALTER COLUMN "propiedadId" DROP NOT NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "transformador_history"."propiedadId" IS NULL`);
        await queryRunner.query(`ALTER TABLE "transformador_history" ALTER COLUMN "efectoId" DROP NOT NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "transformador_history"."efectoId" IS NULL`);
        await queryRunner.query(`ALTER TABLE "transformador" DROP COLUMN "matricula"`);
        await queryRunner.query(`ALTER TABLE "transformador" ADD "matricula" character varying(6) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "transformador" ALTER COLUMN "razonRechazoId" DROP NOT NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "transformador"."razonRechazoId" IS NULL`);
        await queryRunner.query(`ALTER TABLE "transformador_history" ADD CONSTRAINT "FK_f033b07db5030982da70df7994b" FOREIGN KEY ("suplidorId") REFERENCES "transformadores_suplidores"("suplidorId") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "transformador_history" ADD CONSTRAINT "FK_294f12e5fecedcd1e1de7cea1ae" FOREIGN KEY ("valoracionId") REFERENCES "transformadores_valoraciones"("valoracionId") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "transformador_history" ADD CONSTRAINT "FK_873922dbd4e75ba23e0bc0c764f" FOREIGN KEY ("soporteId") REFERENCES "transformadores_soportes"("soporteId") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "transformador_history" ADD CONSTRAINT "FK_cadf2ffc2070b6ae3c716280067" FOREIGN KEY ("tipoSoporteId") REFERENCES "transformadores_tipo_soportes"("tipoSoporteId") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "transformador_history" ADD CONSTRAINT "FK_00f32a9a00c7768f4d30721db7f" FOREIGN KEY ("fabricanteId") REFERENCES "transformadores_fabricantes"("fabricanteId") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "transformador_history" ADD CONSTRAINT "FK_77d477b9f47f827604896a1d648" FOREIGN KEY ("faseId") REFERENCES "transformadores_fases"("faseId") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "transformador_history" ADD CONSTRAINT "FK_8066bbee582e1932895b298bcd1" FOREIGN KEY ("capacidadId") REFERENCES "transformadores_capacidades"("capacidadId") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "transformador_history" ADD CONSTRAINT "FK_8b442a3b3086f4c49e9bc9e9bec" FOREIGN KEY ("conexionId") REFERENCES "transformadores_conexiones"("conexionId") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "transformador_history" ADD CONSTRAINT "FK_fa7d15f339a2159bb0d8fec8276" FOREIGN KEY ("tensionPrimariaId") REFERENCES "transformadores_tension_primaria"("tensionPrimariaId") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "transformador_history" ADD CONSTRAINT "FK_3da885bc55b1ca49c8302086167" FOREIGN KEY ("tensionSecundariaId") REFERENCES "transformadores_tension_secundaria"("tensionSecundariaId") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "transformador_history" ADD CONSTRAINT "FK_02a0444e669dc88919b729f2239" FOREIGN KEY ("regulacionId") REFERENCES "transformadores_regulaciones"("regulacionId") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "transformador_history" ADD CONSTRAINT "FK_1fae3f99d775577b0fbe0def9a2" FOREIGN KEY ("razonRechazoId") REFERENCES "transformadores_razones_rechazo"("razonRechazoId") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "transformador_history" ADD CONSTRAINT "FK_d9c66ff0addd7ff9a5e5f937168" FOREIGN KEY ("usuarioId") REFERENCES "users"("usuarioId") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "transformador_history" ADD CONSTRAINT "FK_7ba52c82488e87e1617dfd25f60" FOREIGN KEY ("estadoId") REFERENCES "transformadores_estados"("estadoId") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "transformador_history" ADD CONSTRAINT "FK_f829abdade15c4d79b4cd02b4ae" FOREIGN KEY ("ubicacionId") REFERENCES "transformadores_ubicacion"("ubicacionId") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "transformador_history" ADD CONSTRAINT "FK_4ffb0c222bfe0c8be0392337c51" FOREIGN KEY ("propiedadId") REFERENCES "transformadores_propiedad"("propiedadId") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "transformador_history" ADD CONSTRAINT "FK_9544b8368a01564f7295939e1ce" FOREIGN KEY ("proyectoId") REFERENCES "proyecto"("proyectoId") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "transformador_history" ADD CONSTRAINT "FK_e3afaa777919c976efe56d10ace" FOREIGN KEY ("efectoId") REFERENCES "transformadores_efecto"("efectoId") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "transformador_history" ADD CONSTRAINT "FK_223f006166dfdd7b491c7032514" FOREIGN KEY ("unidadId") REFERENCES "transformadores_unidades_constructiva"("unidadId") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "transformador" ADD CONSTRAINT "FK_ad6187807839b5384e634b2732e" FOREIGN KEY ("suplidorId") REFERENCES "transformadores_suplidores"("suplidorId") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "transformador" ADD CONSTRAINT "FK_bc1c81f5131471d3e5be8d854c2" FOREIGN KEY ("valoracionId") REFERENCES "transformadores_valoraciones"("valoracionId") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "transformador" ADD CONSTRAINT "FK_7cb6f00533cc57a5a0cdbdbdc72" FOREIGN KEY ("soporteId") REFERENCES "transformadores_soportes"("soporteId") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "transformador" ADD CONSTRAINT "FK_65e540df2def07db88625994549" FOREIGN KEY ("tipoSoporteId") REFERENCES "transformadores_tipo_soportes"("tipoSoporteId") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "transformador" ADD CONSTRAINT "FK_1f5244796dcec496b3b4d990926" FOREIGN KEY ("fabricanteId") REFERENCES "transformadores_fabricantes"("fabricanteId") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "transformador" ADD CONSTRAINT "FK_e95d11ef7089132e3f6a3dcc025" FOREIGN KEY ("faseId") REFERENCES "transformadores_fases"("faseId") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "transformador" ADD CONSTRAINT "FK_7247893fdd6229dfa1b77f2faf6" FOREIGN KEY ("capacidadId") REFERENCES "transformadores_capacidades"("capacidadId") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "transformador" ADD CONSTRAINT "FK_26f4f35b52e5c33a7722e26df65" FOREIGN KEY ("conexionId") REFERENCES "transformadores_conexiones"("conexionId") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "transformador" ADD CONSTRAINT "FK_6e9d49a76f98a376af595a09fb4" FOREIGN KEY ("tensionPrimariaId") REFERENCES "transformadores_tension_primaria"("tensionPrimariaId") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "transformador" ADD CONSTRAINT "FK_b7a6ca44c35ce29b9d08addec5a" FOREIGN KEY ("tensionSecundariaId") REFERENCES "transformadores_tension_secundaria"("tensionSecundariaId") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "transformador" ADD CONSTRAINT "FK_a5ae3455655c057cab39b5e05bd" FOREIGN KEY ("regulacionId") REFERENCES "transformadores_regulaciones"("regulacionId") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "transformador" ADD CONSTRAINT "FK_ac2675c787646dec6806bef12b2" FOREIGN KEY ("razonRechazoId") REFERENCES "transformadores_razones_rechazo"("razonRechazoId") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "transformador" ADD CONSTRAINT "FK_6aa69aab8bbd594fc505e566d07" FOREIGN KEY ("estadoId") REFERENCES "transformadores_estados"("estadoId") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "transformador" ADD CONSTRAINT "FK_234e6869160f95ddbca2b484d7e" FOREIGN KEY ("ubicacionId") REFERENCES "transformadores_ubicacion"("ubicacionId") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "transformador" ADD CONSTRAINT "FK_2772d525909992a88cdca4d54c3" FOREIGN KEY ("propiedadId") REFERENCES "transformadores_propiedad"("propiedadId") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "transformador" ADD CONSTRAINT "FK_2fcf4e1cdd2e2ff44cb4f911a8e" FOREIGN KEY ("proyectoId") REFERENCES "proyecto"("proyectoId") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "transformador" ADD CONSTRAINT "FK_9fbcda37e37efe1eda0eef6313b" FOREIGN KEY ("efectoId") REFERENCES "transformadores_efecto"("efectoId") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "transformador" ADD CONSTRAINT "FK_5c813aae3faeb5e18eab11bc9fb" FOREIGN KEY ("unidadId") REFERENCES "transformadores_unidades_constructiva"("unidadId") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "transformador" DROP CONSTRAINT "FK_5c813aae3faeb5e18eab11bc9fb"`);
        await queryRunner.query(`ALTER TABLE "transformador" DROP CONSTRAINT "FK_9fbcda37e37efe1eda0eef6313b"`);
        await queryRunner.query(`ALTER TABLE "transformador" DROP CONSTRAINT "FK_2fcf4e1cdd2e2ff44cb4f911a8e"`);
        await queryRunner.query(`ALTER TABLE "transformador" DROP CONSTRAINT "FK_2772d525909992a88cdca4d54c3"`);
        await queryRunner.query(`ALTER TABLE "transformador" DROP CONSTRAINT "FK_234e6869160f95ddbca2b484d7e"`);
        await queryRunner.query(`ALTER TABLE "transformador" DROP CONSTRAINT "FK_6aa69aab8bbd594fc505e566d07"`);
        await queryRunner.query(`ALTER TABLE "transformador" DROP CONSTRAINT "FK_ac2675c787646dec6806bef12b2"`);
        await queryRunner.query(`ALTER TABLE "transformador" DROP CONSTRAINT "FK_a5ae3455655c057cab39b5e05bd"`);
        await queryRunner.query(`ALTER TABLE "transformador" DROP CONSTRAINT "FK_b7a6ca44c35ce29b9d08addec5a"`);
        await queryRunner.query(`ALTER TABLE "transformador" DROP CONSTRAINT "FK_6e9d49a76f98a376af595a09fb4"`);
        await queryRunner.query(`ALTER TABLE "transformador" DROP CONSTRAINT "FK_26f4f35b52e5c33a7722e26df65"`);
        await queryRunner.query(`ALTER TABLE "transformador" DROP CONSTRAINT "FK_7247893fdd6229dfa1b77f2faf6"`);
        await queryRunner.query(`ALTER TABLE "transformador" DROP CONSTRAINT "FK_e95d11ef7089132e3f6a3dcc025"`);
        await queryRunner.query(`ALTER TABLE "transformador" DROP CONSTRAINT "FK_1f5244796dcec496b3b4d990926"`);
        await queryRunner.query(`ALTER TABLE "transformador" DROP CONSTRAINT "FK_65e540df2def07db88625994549"`);
        await queryRunner.query(`ALTER TABLE "transformador" DROP CONSTRAINT "FK_7cb6f00533cc57a5a0cdbdbdc72"`);
        await queryRunner.query(`ALTER TABLE "transformador" DROP CONSTRAINT "FK_bc1c81f5131471d3e5be8d854c2"`);
        await queryRunner.query(`ALTER TABLE "transformador" DROP CONSTRAINT "FK_ad6187807839b5384e634b2732e"`);
        await queryRunner.query(`ALTER TABLE "transformador_history" DROP CONSTRAINT "FK_223f006166dfdd7b491c7032514"`);
        await queryRunner.query(`ALTER TABLE "transformador_history" DROP CONSTRAINT "FK_e3afaa777919c976efe56d10ace"`);
        await queryRunner.query(`ALTER TABLE "transformador_history" DROP CONSTRAINT "FK_9544b8368a01564f7295939e1ce"`);
        await queryRunner.query(`ALTER TABLE "transformador_history" DROP CONSTRAINT "FK_4ffb0c222bfe0c8be0392337c51"`);
        await queryRunner.query(`ALTER TABLE "transformador_history" DROP CONSTRAINT "FK_f829abdade15c4d79b4cd02b4ae"`);
        await queryRunner.query(`ALTER TABLE "transformador_history" DROP CONSTRAINT "FK_7ba52c82488e87e1617dfd25f60"`);
        await queryRunner.query(`ALTER TABLE "transformador_history" DROP CONSTRAINT "FK_d9c66ff0addd7ff9a5e5f937168"`);
        await queryRunner.query(`ALTER TABLE "transformador_history" DROP CONSTRAINT "FK_1fae3f99d775577b0fbe0def9a2"`);
        await queryRunner.query(`ALTER TABLE "transformador_history" DROP CONSTRAINT "FK_02a0444e669dc88919b729f2239"`);
        await queryRunner.query(`ALTER TABLE "transformador_history" DROP CONSTRAINT "FK_3da885bc55b1ca49c8302086167"`);
        await queryRunner.query(`ALTER TABLE "transformador_history" DROP CONSTRAINT "FK_fa7d15f339a2159bb0d8fec8276"`);
        await queryRunner.query(`ALTER TABLE "transformador_history" DROP CONSTRAINT "FK_8b442a3b3086f4c49e9bc9e9bec"`);
        await queryRunner.query(`ALTER TABLE "transformador_history" DROP CONSTRAINT "FK_8066bbee582e1932895b298bcd1"`);
        await queryRunner.query(`ALTER TABLE "transformador_history" DROP CONSTRAINT "FK_77d477b9f47f827604896a1d648"`);
        await queryRunner.query(`ALTER TABLE "transformador_history" DROP CONSTRAINT "FK_00f32a9a00c7768f4d30721db7f"`);
        await queryRunner.query(`ALTER TABLE "transformador_history" DROP CONSTRAINT "FK_cadf2ffc2070b6ae3c716280067"`);
        await queryRunner.query(`ALTER TABLE "transformador_history" DROP CONSTRAINT "FK_873922dbd4e75ba23e0bc0c764f"`);
        await queryRunner.query(`ALTER TABLE "transformador_history" DROP CONSTRAINT "FK_294f12e5fecedcd1e1de7cea1ae"`);
        await queryRunner.query(`ALTER TABLE "transformador_history" DROP CONSTRAINT "FK_f033b07db5030982da70df7994b"`);
        await queryRunner.query(`COMMENT ON COLUMN "transformador"."razonRechazoId" IS NULL`);
        await queryRunner.query(`ALTER TABLE "transformador" ALTER COLUMN "razonRechazoId" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "transformador" DROP COLUMN "matricula"`);
        await queryRunner.query(`ALTER TABLE "transformador" ADD "matricula" character varying NOT NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "transformador_history"."efectoId" IS NULL`);
        await queryRunner.query(`ALTER TABLE "transformador_history" ALTER COLUMN "efectoId" SET NOT NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "transformador_history"."propiedadId" IS NULL`);
        await queryRunner.query(`ALTER TABLE "transformador_history" ALTER COLUMN "propiedadId" SET NOT NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "transformador_history"."ubicacionId" IS NULL`);
        await queryRunner.query(`ALTER TABLE "transformador_history" ALTER COLUMN "ubicacionId" SET NOT NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "transformador_history"."estadoId" IS NULL`);
        await queryRunner.query(`ALTER TABLE "transformador_history" ALTER COLUMN "estadoId" SET NOT NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "transformador_history"."razonRechazoId" IS NULL`);
        await queryRunner.query(`ALTER TABLE "transformador_history" ALTER COLUMN "razonRechazoId" SET NOT NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "transformador_history"."regulacionId" IS NULL`);
        await queryRunner.query(`ALTER TABLE "transformador_history" ALTER COLUMN "regulacionId" SET NOT NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "transformador_history"."tensionSecundariaId" IS NULL`);
        await queryRunner.query(`ALTER TABLE "transformador_history" ALTER COLUMN "tensionSecundariaId" SET NOT NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "transformador_history"."tensionPrimariaId" IS NULL`);
        await queryRunner.query(`ALTER TABLE "transformador_history" ALTER COLUMN "tensionPrimariaId" SET NOT NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "transformador_history"."conexionId" IS NULL`);
        await queryRunner.query(`ALTER TABLE "transformador_history" ALTER COLUMN "conexionId" SET NOT NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "transformador_history"."capacidadId" IS NULL`);
        await queryRunner.query(`ALTER TABLE "transformador_history" ALTER COLUMN "capacidadId" SET NOT NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "transformador_history"."faseId" IS NULL`);
        await queryRunner.query(`ALTER TABLE "transformador_history" ALTER COLUMN "faseId" SET NOT NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "transformador_history"."fabricanteId" IS NULL`);
        await queryRunner.query(`ALTER TABLE "transformador_history" ALTER COLUMN "fabricanteId" SET NOT NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "transformador_history"."tipoSoporteId" IS NULL`);
        await queryRunner.query(`ALTER TABLE "transformador_history" ALTER COLUMN "tipoSoporteId" SET NOT NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "transformador_history"."soporteId" IS NULL`);
        await queryRunner.query(`ALTER TABLE "transformador_history" ALTER COLUMN "soporteId" SET NOT NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "transformador_history"."valoracionId" IS NULL`);
        await queryRunner.query(`ALTER TABLE "transformador_history" ALTER COLUMN "valoracionId" SET NOT NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "transformador_history"."suplidorId" IS NULL`);
        await queryRunner.query(`ALTER TABLE "transformador_history" ALTER COLUMN "suplidorId" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "transformador_history" DROP COLUMN "matricula"`);
        await queryRunner.query(`ALTER TABLE "transformador_history" ADD "matricula" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "transformador" DROP COLUMN "unidadId"`);
        await queryRunner.query(`ALTER TABLE "transformador" DROP COLUMN "efectoId"`);
        await queryRunner.query(`ALTER TABLE "transformador" DROP COLUMN "proyectoId"`);
        await queryRunner.query(`ALTER TABLE "transformador" DROP COLUMN "propiedadId"`);
        await queryRunner.query(`ALTER TABLE "transformador" DROP COLUMN "ubicacionId"`);
        await queryRunner.query(`ALTER TABLE "transformador" DROP COLUMN "estadoId"`);
        await queryRunner.query(`ALTER TABLE "transformador" DROP COLUMN "regulacionId"`);
        await queryRunner.query(`ALTER TABLE "transformador" DROP COLUMN "tensionSecundariaId"`);
        await queryRunner.query(`ALTER TABLE "transformador" DROP COLUMN "tensionPrimariaId"`);
        await queryRunner.query(`ALTER TABLE "transformador" DROP COLUMN "conexionId"`);
        await queryRunner.query(`ALTER TABLE "transformador" DROP COLUMN "capacidadId"`);
        await queryRunner.query(`ALTER TABLE "transformador" DROP COLUMN "faseId"`);
        await queryRunner.query(`ALTER TABLE "transformador" DROP COLUMN "fabricanteId"`);
        await queryRunner.query(`ALTER TABLE "transformador" DROP COLUMN "tipoSoporteId"`);
        await queryRunner.query(`ALTER TABLE "transformador" DROP COLUMN "soporteId"`);
        await queryRunner.query(`ALTER TABLE "transformador" DROP COLUMN "valoracionId"`);
        await queryRunner.query(`ALTER TABLE "transformador" DROP COLUMN "suplidorId"`);
        await queryRunner.query(`ALTER TABLE "transformador" DROP CONSTRAINT "PK_203aa7cf691c0663fe5ac65b023"`);
        await queryRunner.query(`ALTER TABLE "transformador" DROP COLUMN "transformadorId"`);
        await queryRunner.query(`ALTER TABLE "transformador_history" DROP COLUMN "unidadId"`);
        await queryRunner.query(`ALTER TABLE "transformador_history" DROP COLUMN "proyectoId"`);
        await queryRunner.query(`ALTER TABLE "transformador_history" DROP COLUMN "usuarioId"`);
        await queryRunner.query(`ALTER TABLE "transformador_history" DROP CONSTRAINT "PK_178e12c3a9f7ee66001d33763f0"`);
        await queryRunner.query(`ALTER TABLE "transformador_history" DROP COLUMN "transformadorId"`);
        await queryRunner.query(`ALTER TABLE "transformadores_tipo_soportes" DROP CONSTRAINT "UQ_668d39a1a240327ffb49201f9b2"`);
        await queryRunner.query(`ALTER TABLE "transformadores_tipo_soportes" DROP COLUMN "tipoSoporte"`);
        await queryRunner.query(`ALTER TABLE "transformadores_tipo_soportes" DROP CONSTRAINT "PK_8839f8c08c17419816a22b3e303"`);
        await queryRunner.query(`ALTER TABLE "transformadores_tipo_soportes" DROP COLUMN "tipoSoporteId"`);
        await queryRunner.query(`ALTER TABLE "transformador" ADD "id_unidad" integer`);
        await queryRunner.query(`ALTER TABLE "transformador" ADD "id_efecto" integer`);
        await queryRunner.query(`ALTER TABLE "transformador" ADD "id_proyecto" integer`);
        await queryRunner.query(`ALTER TABLE "transformador" ADD "id_propiedad" integer`);
        await queryRunner.query(`ALTER TABLE "transformador" ADD "id_ubicacion" integer`);
        await queryRunner.query(`ALTER TABLE "transformador" ADD "id_estado" integer`);
        await queryRunner.query(`ALTER TABLE "transformador" ADD "id_regulacion" integer`);
        await queryRunner.query(`ALTER TABLE "transformador" ADD "id_tension_secundaria" integer`);
        await queryRunner.query(`ALTER TABLE "transformador" ADD "id_tension_primaria" integer`);
        await queryRunner.query(`ALTER TABLE "transformador" ADD "id_conexion" integer`);
        await queryRunner.query(`ALTER TABLE "transformador" ADD "id_capacidad" integer`);
        await queryRunner.query(`ALTER TABLE "transformador" ADD "id_fase" integer`);
        await queryRunner.query(`ALTER TABLE "transformador" ADD "id_fabricante" integer`);
        await queryRunner.query(`ALTER TABLE "transformador" ADD "id_tipo_soporte" integer`);
        await queryRunner.query(`ALTER TABLE "transformador" ADD "id_soporte" integer`);
        await queryRunner.query(`ALTER TABLE "transformador" ADD "id_valoracion" integer`);
        await queryRunner.query(`ALTER TABLE "transformador" ADD "id_suplidor" integer`);
        await queryRunner.query(`ALTER TABLE "transformador" ADD "id" SERIAL NOT NULL`);
        await queryRunner.query(`ALTER TABLE "transformador" ADD CONSTRAINT "PK_ff9524e64fceca6e12d390d71c5" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "transformador_history" ADD "usuarioIdUsuarioId" integer`);
        await queryRunner.query(`ALTER TABLE "transformador_history" ADD CONSTRAINT "UQ_49a611aee89b4888fc40fae3b83" UNIQUE ("usuarioIdUsuarioId")`);
        await queryRunner.query(`ALTER TABLE "transformador_history" ADD "codigoSap" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "transformador_history" ADD "codigoProyecto" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "transformador_history" ADD "nombreProyecto" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "transformador_history" ADD "id" SERIAL NOT NULL`);
        await queryRunner.query(`ALTER TABLE "transformador_history" ADD CONSTRAINT "PK_0085c3c9b93a0379203566f79ab" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "transformadores_tipo_soportes" ADD "tipo_soporte" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "transformadores_tipo_soportes" ADD CONSTRAINT "UQ_b0fe91b2b70fcca603cf7d2ff93" UNIQUE ("tipo_soporte")`);
        await queryRunner.query(`ALTER TABLE "transformadores_tipo_soportes" ADD "id_tipo_soporte" SERIAL NOT NULL`);
        await queryRunner.query(`ALTER TABLE "transformadores_tipo_soportes" ADD CONSTRAINT "PK_a6dd05052e83b7fd1508bdadc68" PRIMARY KEY ("id_tipo_soporte")`);
        await queryRunner.query(`ALTER SEQUENCE "transformadores_valoraciones_valoracionId_seq" RENAME TO "transformadores_valoraciones_id_valoracion_seq"`);
        await queryRunner.query(`ALTER TABLE "transformadores_valoraciones" RENAME CONSTRAINT "PK_e93a53b867248142f4546b1998b" TO "PK_dc50231888c0809221e561a7def"`);
        await queryRunner.query(`ALTER TABLE "transformadores_valoraciones" RENAME COLUMN "valoracionId" TO "id_valoracion"`);
        await queryRunner.query(`ALTER SEQUENCE "transformadores_unidades_constructiva_unidadId_seq" RENAME TO "transformadores_unidades_constructiva_id_unidad_seq"`);
        await queryRunner.query(`ALTER TABLE "transformadores_unidades_constructiva" RENAME CONSTRAINT "PK_4e341b5338c1d26b0f4eb847bd1" TO "PK_62e8d7d29ae24f63be4f2bd2c15"`);
        await queryRunner.query(`ALTER TABLE "transformadores_unidades_constructiva" RENAME COLUMN "unidadId" TO "id_unidad"`);
        await queryRunner.query(`ALTER SEQUENCE "transformadores_ubicacion_ubicacionId_seq" RENAME TO "transformadores_ubicacion_id_ubicacion_seq"`);
        await queryRunner.query(`ALTER TABLE "transformadores_ubicacion" RENAME CONSTRAINT "PK_124a7e146c6342fddc827714bf6" TO "PK_385f8f855d9cfacec35b43f2738"`);
        await queryRunner.query(`ALTER TABLE "transformadores_ubicacion" RENAME COLUMN "ubicacionId" TO "id_ubicacion"`);
        await queryRunner.query(`ALTER SEQUENCE "transformadores_tipo_reparacion_tipoReparacionId_seq" RENAME TO "transformadores_tipo_reparacion_id_tipo_reparacion_seq"`);
        await queryRunner.query(`ALTER TABLE "transformadores_tipo_reparacion" RENAME CONSTRAINT "PK_49202691f772e3f1cbd062da25e" TO "PK_2d1dc5624e4a0c26f436065d457"`);
        await queryRunner.query(`ALTER TABLE "transformadores_tipo_reparacion" RENAME COLUMN "tipoReparacionId" TO "id_tipo_reparacion"`);
        await queryRunner.query(`ALTER SEQUENCE "transformadores_tension_secundaria_tensionSecundariaId_seq" RENAME TO "transformadores_tension_secundaria_id_tension_secundaria_seq"`);
        await queryRunner.query(`ALTER TABLE "transformadores_tension_secundaria" RENAME CONSTRAINT "PK_a6998508c1973c6b7c0e039db63" TO "PK_ab0ca604c7ffc6ab3e506e6b35f"`);
        await queryRunner.query(`ALTER TABLE "transformadores_tension_secundaria" RENAME COLUMN "tensionSecundariaId" TO "id_tension_secundaria"`);
        await queryRunner.query(`ALTER SEQUENCE "transformadores_tension_primaria_tensionPrimariaId_seq" RENAME TO "transformadores_tension_primaria_id_tension_primaria_seq"`);
        await queryRunner.query(`ALTER TABLE "transformadores_tension_primaria" RENAME CONSTRAINT "PK_c09d6bd5e2ef3ce051cd2230a36" TO "PK_b147cc945f0c090bc6217a054bd"`);
        await queryRunner.query(`ALTER TABLE "transformadores_tension_primaria" RENAME COLUMN "tensionPrimariaId" TO "id_tension_primaria"`);
        await queryRunner.query(`ALTER SEQUENCE "transformadores_suplidores_suplidorId_seq" RENAME TO "transformadores_suplidores_id_suplidor_seq"`);
        await queryRunner.query(`ALTER TABLE "transformadores_suplidores" RENAME CONSTRAINT "PK_5d77c13ae641f238e6ecad9f03b" TO "PK_76510d1d136e8d1834c286de77c"`);
        await queryRunner.query(`ALTER TABLE "transformadores_suplidores" RENAME COLUMN "suplidorId" TO "id_suplidor"`);
        await queryRunner.query(`ALTER SEQUENCE "transformadores_soportes_soporteId_seq" RENAME TO "transformadores_soportes_id_soporte_seq"`);
        await queryRunner.query(`ALTER TABLE "transformadores_soportes" RENAME CONSTRAINT "PK_7c8bd6cc594d72b2865244362d2" TO "PK_c2e5519a97aed89f951b9125fde"`);
        await queryRunner.query(`ALTER TABLE "transformadores_soportes" RENAME COLUMN "soporteId" TO "id_soporte"`);
        await queryRunner.query(`ALTER SEQUENCE "transformadores_regulaciones_regulacionId_seq" RENAME TO "transformadores_regulaciones_id_regulacion_seq"`);
        await queryRunner.query(`ALTER TABLE "transformadores_regulaciones" RENAME CONSTRAINT "PK_801e2d41d7541bf7ee2ed103bcf" TO "PK_630f22d451333479bd1bfd41d91"`);
        await queryRunner.query(`ALTER TABLE "transformadores_regulaciones" RENAME COLUMN "regulacionId" TO "id_regulacion"`);
        await queryRunner.query(`ALTER SEQUENCE "transformadores_razones_rechazo_razonRechazoId_seq" RENAME TO "transformadores_razones_rechazo_id_razon_seq"`);
        await queryRunner.query(`ALTER TABLE "transformadores_razones_rechazo" RENAME CONSTRAINT "PK_058530b50659ab358b9c35b4567" TO "PK_e5984dbf9e1dcbb8a9def0d0118"`);
        await queryRunner.query(`ALTER TABLE "transformadores_razones_rechazo" RENAME COLUMN "razonRechazoId" TO "id_razon"`);
        await queryRunner.query(`ALTER SEQUENCE "transformadores_propiedad_propiedadId_seq" RENAME TO "transformadores_propiedad_id_propiedad_seq"`);
        await queryRunner.query(`ALTER TABLE "transformadores_propiedad" RENAME CONSTRAINT "PK_6adcff562dbe44c73e3d37fd4ad" TO "PK_d647dbb6eb5d7931fc47462d8b5"`);
        await queryRunner.query(`ALTER TABLE "transformadores_propiedad" RENAME COLUMN "propiedadId" TO "id_propiedad"`);
        await queryRunner.query(`ALTER SEQUENCE "transformadores_fases_faseId_seq" RENAME TO "transformadores_fases_id_fase_seq"`);
        await queryRunner.query(`ALTER TABLE "transformadores_fases" RENAME CONSTRAINT "PK_20749f59de4212e35823bc06c09" TO "PK_3c676769b9d2ce253994d947e83"`);
        await queryRunner.query(`ALTER TABLE "transformadores_fases" RENAME COLUMN "faseId" TO "id_fase"`);
        await queryRunner.query(`ALTER SEQUENCE "transformadores_fabricantes_fabricanteId_seq" RENAME TO "transformadores_fabricantes_id_fabricante_seq"`);
        await queryRunner.query(`ALTER TABLE "transformadores_fabricantes" RENAME CONSTRAINT "PK_96ff1c88cbe4a1d56233987f1c2" TO "PK_82d72a72eacec5188ad9df70c71"`);
        await queryRunner.query(`ALTER TABLE "transformadores_fabricantes" RENAME COLUMN "fabricanteId" TO "id_fabricante"`);
        await queryRunner.query(`ALTER SEQUENCE "transformadores_resultados_evaluacion_resultadoEvaluacionId_seq" RENAME TO "transformadores_resultados_evaluacion_id_resultado_seq"`);
        await queryRunner.query(`ALTER TABLE "transformadores_resultados_evaluacion" RENAME CONSTRAINT "PK_20d2cbc6e75e182556df2febbde" TO "PK_d6a952504dab1d399e57479e6aa"`);
        await queryRunner.query(`ALTER TABLE "transformadores_resultados_evaluacion" RENAME COLUMN "resultadoEvaluacionId" TO "id_resultado"`);
        await queryRunner.query(`ALTER SEQUENCE "transformadores_estados_estadoId_seq" RENAME TO "transformadores_estados_id_estado_seq"`);
        await queryRunner.query(`ALTER TABLE "transformadores_estados" RENAME CONSTRAINT "PK_d00dac79de670d9c19260e0fa67" TO "PK_df6bac6af1079e757686d988ac4"`);
        await queryRunner.query(`ALTER TABLE "transformadores_estados" RENAME COLUMN "estadoId" TO "id_estado"`);
        await queryRunner.query(`ALTER SEQUENCE "transformadores_efecto_efectoId_seq" RENAME TO "transformadores_efecto_id_efecto_seq"`);
        await queryRunner.query(`ALTER TABLE "transformadores_efecto" RENAME CONSTRAINT "PK_dc6c0ce8ed39e021e1d076d1903" TO "PK_af57613b05f91684990faa28ab5"`);
        await queryRunner.query(`ALTER TABLE "transformadores_efecto" RENAME COLUMN "efectoId" TO "id_efecto"`);
        await queryRunner.query(`ALTER SEQUENCE "transformadores_conexiones_conexionId_seq" RENAME TO "transformadores_conexiones_id_conexion_seq"`);
        await queryRunner.query(`ALTER TABLE "transformadores_conexiones" RENAME CONSTRAINT "PK_b065af150910fd14b0afd587cab" TO "PK_771c4032e20dce521e09b5524fd"`);
        await queryRunner.query(`ALTER TABLE "transformadores_conexiones" RENAME COLUMN "conexionId" TO "id_conexion"`);
        await queryRunner.query(`ALTER SEQUENCE "transformadores_capacidades_capacidadId_seq" RENAME TO "transformadores_capacidades_id_capacidad_seq"`);
        await queryRunner.query(`ALTER TABLE "transformadores_capacidades" RENAME CONSTRAINT "PK_875e138bf3b3069e7b65c7e6f91" TO "PK_4d5d9842b4f280405d736e98671"`);
        await queryRunner.query(`ALTER TABLE "transformadores_capacidades" RENAME COLUMN "capacidadId" TO "id_capacidad"`);
        await queryRunner.query(`ALTER SEQUENCE "proyecto_proyectoId_seq" RENAME TO "proyecto_id_proyecto_seq"`);
        await queryRunner.query(`ALTER TABLE "proyecto" RENAME CONSTRAINT "PK_696214b6444b9d109f850c82367" TO "PK_5ecc7af27ab7fa5ed5243d437c4"`);
        await queryRunner.query(`ALTER TABLE "proyecto" RENAME COLUMN "proyectoId" TO "id_proyecto"`);
        await queryRunner.query(`ALTER TABLE "transformador" ADD CONSTRAINT "FK_f1ef0c13a22619d647cc66093ba" FOREIGN KEY ("id_suplidor") REFERENCES "transformadores_suplidores"("id_suplidor") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "transformador" ADD CONSTRAINT "FK_48780be18e0949239689231edd3" FOREIGN KEY ("id_valoracion") REFERENCES "transformadores_valoraciones"("id_valoracion") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "transformador" ADD CONSTRAINT "FK_7607ee4991b934b0e877a790abc" FOREIGN KEY ("id_soporte") REFERENCES "transformadores_soportes"("id_soporte") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "transformador" ADD CONSTRAINT "FK_a8e4b8f5b885febe2dcd413f1a4" FOREIGN KEY ("id_tipo_soporte") REFERENCES "transformadores_tipo_soportes"("id_tipo_soporte") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "transformador" ADD CONSTRAINT "FK_911c5b898a45f67be711fb7f1bf" FOREIGN KEY ("id_fabricante") REFERENCES "transformadores_fabricantes"("id_fabricante") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "transformador" ADD CONSTRAINT "FK_964e13208e8b5916303b1fe3729" FOREIGN KEY ("id_fase") REFERENCES "transformadores_fases"("id_fase") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "transformador" ADD CONSTRAINT "FK_491465c988d13ad4ba1702439b6" FOREIGN KEY ("id_capacidad") REFERENCES "transformadores_capacidades"("id_capacidad") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "transformador" ADD CONSTRAINT "FK_9b63dde044777cafa4f268b8ba9" FOREIGN KEY ("id_conexion") REFERENCES "transformadores_conexiones"("id_conexion") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "transformador" ADD CONSTRAINT "FK_e7f25b0482d13195e4c08807c2c" FOREIGN KEY ("id_tension_primaria") REFERENCES "transformadores_tension_primaria"("id_tension_primaria") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "transformador" ADD CONSTRAINT "FK_a39a2fc8d1fd728d443dfa23507" FOREIGN KEY ("id_tension_secundaria") REFERENCES "transformadores_tension_secundaria"("id_tension_secundaria") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "transformador" ADD CONSTRAINT "FK_d5dcfb16a204473788f69a57c63" FOREIGN KEY ("id_regulacion") REFERENCES "transformadores_regulaciones"("id_regulacion") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "transformador" ADD CONSTRAINT "FK_25168a4af0dc7dee21b9060ff9c" FOREIGN KEY ("id_estado") REFERENCES "transformadores_estados"("id_estado") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "transformador" ADD CONSTRAINT "FK_5735d8b4e488bf40c02d6235eae" FOREIGN KEY ("id_ubicacion") REFERENCES "transformadores_ubicacion"("id_ubicacion") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "transformador" ADD CONSTRAINT "FK_033c270499f6016fbe8ce8109f4" FOREIGN KEY ("id_propiedad") REFERENCES "transformadores_propiedad"("id_propiedad") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "transformador" ADD CONSTRAINT "FK_2fdec658590e3659e8264437cbe" FOREIGN KEY ("id_proyecto") REFERENCES "proyecto"("id_proyecto") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "transformador" ADD CONSTRAINT "FK_1dbc5c073b79860a90a4f0a5357" FOREIGN KEY ("id_efecto") REFERENCES "transformadores_efecto"("id_efecto") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "transformador" ADD CONSTRAINT "FK_0811119ad82d3f12b8868e7886f" FOREIGN KEY ("id_unidad") REFERENCES "transformadores_unidades_constructiva"("id_unidad") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "transformador_history" ADD CONSTRAINT "FK_49a611aee89b4888fc40fae3b83" FOREIGN KEY ("usuarioIdUsuarioId") REFERENCES "users"("usuarioId") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

}
